# this goes inside _config.yml. Change as required
navigation:
        - text: Home
          url: /index.html
        - text: Download
          url: /download.html
        - text: Documentation
          url: /docs.html
        - text: Publications
          url: /pubs.html
#        - text: Datasets
#          url: /data.html
        - text: People
          url: /people.html

toolname: Nichrome
